services:
  reverse_proxy_macos:
    image: docker.io/library/traefik:v2.10
    command:
      # Rules
      - --providers.file=true
      - --providers.file.filename=/etc/traefik/rules.yaml
      - --providers.file.watch=true

      # API and dashboard
      - '--api.insecure=true'
      - '--api.dashboard=true'

      # Entry points configuration
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'

      # HTTP/2 configuration (critical for subscriptions)
      - '--entrypoints.websecure.http.tls=true'
      - '--entrypoints.websecure.http2.maxConcurrentStreams=250'

      # HTTP to HTTPS redirect
      # - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      # - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - './util/traefik_docker.yaml:/etc/traefik/rules.yaml'
      - './util/ssl:/etc/certs:ro'
    networks:
      - demo-game

  postgres:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    networks:
      - demo-game

networks:
  demo-game:
