services:
  postgres:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    networks:
      - demo-game

networks:
  demo-game:
