services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    networks:
      - demo-game

networks:
  demo-game:
