packages:
  - 'apps/*'
  - 'packages/*'
  - cypress
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  core-js: false
  cypress: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
